lochimban/loaCompass

frontend/src/App.jsx, frontend/src/components/CharacterSearchInput.jsx, frontend/src/components/DarkToggle.jsx, frontend/src/components/Navbar.jsx, frontend/src/hooks/useDarkMode.js, frontend/src/index.css, frontend/src/main.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/pages/Home.jsx, frontend/src/routes/AppRouter.jsx
---
---
---
---
---
- 리뷰 요청: @YJOH11
=> 유저검색, 홈화면다크모드

backend/build.gradle, backend/src/main/java/com/finalteam/loacompass/controller/ShopController.java, backend/src/main/java/com/finalteam/loacompass/controller/ShopSeleniumController.java, backend/src/main/java/com/finalteam/loacompass/controller/UpdateController.java, frontend/src/components/ShopList.jsx, frontend/src/components/UpdateList.jsx, frontend/src/pages/Home.jsx
마리샵(시간은 나중에)
---
마리샵(시간은 나중에)
이게 크롬드라이버 설치해야함 (스샷부분 참고)
---
---
현재 판매하는거만 뜨게함
https://googlechromelabs.github.io/chrome-for-testing/
크롬 드라이버라고 써져있는거 자기 컴터버전 맞는거 다운 받으셈
그리고 "C:/chromedriver/chromedriver.exe" 이부분에 놓으셈
마리샵이 api도 없는거같고 크롤링으로 한건데 문자만 있음 상관없는데 이미지도 있고 해서 이런방법이 필요한거같음 
---
---
- 리뷰 요청: @YJOH11
=> 마리샵(시간은 나중에)

frontend/src/pages/Home.jsx, frontend/src/pages/SassagaeCrawler.jsx
home에 dev안닫힌거 수정
---
home에 dev안닫힌거 수정
---
---
(필요 시 스크린샷 첨부)
---
---
- 리뷰 요청
=> home에 dev안닫힌거 수정

backend/src/main/java/com/finalteam/loacompass/dto/ElixirOptionDto.java, backend/src/main/java/com/finalteam/loacompass/dto/EquipmentDto.java, backend/src/main/java/com/finalteam/loacompass/util/TooltipParser.java, frontend/src/pages/CharacterSearch.jsx
캐릭터랑 장비 이미지 띄우고  장비부분 수치 디테일하게 들어가도록 조정.(엘릭서, 엘릭서 옵션+레벨)
근데 몇몇 캐릭터들이 엘릭서 옵션이 안뜸.. 추후 코드 손볼 예정
초월 ,  악세서리 , 팔찌, 돌 옵션들은 아직 구현 안됨 
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> Oyj 캐릭터 정보화면 구성중

backend/src/main/java/com/finalteam/loacompass/client/LostArkClient.java, backend/src/main/java/com/finalteam/loacompass/dto/EquipmentDto.java, backend/src/main/java/com/finalteam/loacompass/util/TooltipParser.java, frontend/src/components/EquipmentCard.jsx, frontend/src/pages/CharacterSearch.jsx
---
이제 장비외에 악세서리 정보도 나오게 수정함
아직 안된것:
-돌이랑 팔찌 정보 추가해야됨
-보석 추가해야됨
-카드 추가해야됨
-획득처 항목은 임시로 해놨는데  나중에 복잡해질거같으면 삭제예정
-데이터들 위치 배치(디자인) 아직 안한상태.
---
---
(필요 시 스크린샷 첨부)
---
---
=> 캐릭터 정보화면 악세서리 정보 추가+@

backend/src/main/java/com/finalteam/loacompass/controller/ShopSeleniumController.java, frontend/src/App.jsx, frontend/src/components/CharacterSearchInput.jsx, frontend/src/components/EquipmentCard.jsx, frontend/src/components/Navbar.jsx, frontend/src/components/ShopList.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/SassagaeCrawler.jsx, frontend/tailwind.config.js
=> 다크모드 화이트모드

backend/build.gradle, backend/src/main/java/com/finalteam/loacompass/config/WebConfig.java, backend/src/main/java/com/finalteam/loacompass/controller/DiscordAuthController.java, backend/src/main/java/com/finalteam/loacompass/controller/DiscordAuthRequest.java, backend/src/main/java/com/finalteam/loacompass/dto/DiscordTokenResponse.java, backend/src/main/java/com/finalteam/loacompass/dto/DiscordUserResponse.java, backend/src/main/java/com/finalteam/loacompass/service/DiscordAuthService.java, backend/src/main/resources/application.yml, frontend/src/components/DiscordLoginButton.jsx, frontend/src/components/Navbar.jsx, frontend/src/pages/DiscordCallback.jsx, frontend/src/pages/NotFound.jsx, frontend/src/routes/AppRouter.jsx
discode login
---
discode login 만듬 설명은ㅇ ㅏ래
---
---
(필요 시 스크린샷 첨부)
로그인 성공화면
전에 로스크 아크 api처럼 환경변수 쓰면됨
이렇게
아이디랑 키랑 url은 카톡으로 보내줌 (보안위험)
---
---
=> discode login

frontend/src/components/Navbar.jsx, frontend/src/pages/Home.jsx
모든이벤트보기 공식홈페이지 연결, 메인로고옆 아이콘 추가
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 모든이벤트보기 공식홈페이지 연결, 메인로고옆 아이콘 추가

frontend/src/components/DiscordLoginButton.jsx, frontend/src/components/Navbar.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/Register.jsx, frontend/src/routes/AppRouter.jsx
login,register 폼만 만듬 아직 기능구현은 안됨
---
---
---
---
---
=> login,register

app.py, backend/src/main/java/com/finalteam/loacompass/controller/ShopSeleniumController.java, backend/src/main/java/com/finalteam/loacompass/crawling/client/FlaskMariShopClient.java, backend/src/main/java/com/finalteam/loacompass/crawling/controller/MariShopProxyController.java, backend/src/main/java/com/finalteam/loacompass/crawling/dto/MariShopItemDto.java, backend/src/main/java/com/finalteam/loacompass/crawling/dto/MariShopResponseDto.java, frontend/src/components/ShopList.jsx, frontend/vite.config.js
1. 크롤링 서버(flask) 실행 명령어:
python app.py
2. 만약 flask 모듈이 안깔려있다면:
pip install flask flask-cors selenium
설치후 python app.py
서버 주소는 http://localhost:5000/
---
loaCompass 경로에   app.py  <- 이 파일이 원래  flask모듈 사용해서 사사게 크롤링 서버(5000) 돌리고 처리하는 곳이었는데
테스트겸 마리샵만 먼저 추가했습니다. 이후 이벤트크롤링이랑,  통계크롤링도 여기에서 추가할예정.
기존에 만들어져있던 ShopSeleniumController.java는  스프링에서 호출하는거기때문에 일단 주석처리(이후 깔끔하게 삭제해도됨)
---
백앤드 api 는  http://localhost:5000/api/shop-mari    <- json 잘나오나 확인용
app.py   위치 참고
---
크롤링 관련 코드들은 이제   loacompass 밑에   crawling  패키지 안에서 따로 작업합니다
---
프론트에서 마리샵  api 호출하는 부분만 바뀐 경로로 수정했습니다(Shop.jsx)
+ 원래 
const res = await axios.get('http://localhost:8080/api/shop');
이런식으로  로컬호스트8080 다 명시했는데  배포과정에서 이렇게하면 꼬일수있다고합니다
그래서 vite.config.js  파일서 프록시 설정 따로해줬습니다.  이제  프론트에서 api 호출할때  
const res = await axios.get('/api/shop'); …
=> 마리샵 크롤링 서버로 이전+프론트에서 api호출할때 경로설정 간소화

app.py, frontend/src/components/ShopList.jsx
이전까지는 크롤링해온 json에 가격부분이 빈배열로 나왔는데
크롤링해오는 홈페이지 뜯어서 확인해보니까   우리가 가격 정보가져오는 코드 양식이 달랐음
우리는 class name . "list_price" 이런식으로 찾으려고했는데
실제 html구조는 
이런식.
해당내용 반영해서 app.py에 반영.
그리고 폰트 색깔이랑 크리스탈 이미지 넣으려고 shoplist.jsx 수정했는데
만족스러운 크리스탈 이미지를 못찾음.  일단 이모티콘으로 넣어놨음.
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> fix marishop price logic

frontend/src/components/Advertisement.jsx, frontend/src/components/EventSection.jsx, frontend/src/components/ShopList.jsx, frontend/src/components/WelcomeBanner.jsx, frontend/src/pages/Home.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> home.jsx에 있는거 컴포넌트해서 분리함

backend/build.gradle, backend/src/main/java/com/finalteam/loacompass/config/PasswordConfig.java, backend/src/main/java/com/finalteam/loacompass/controller/AuthController.java, backend/src/main/java/com/finalteam/loacompass/dto/JwtResponse.java, backend/src/main/java/com/finalteam/loacompass/dto/LoginRequest.java, backend/src/main/java/com/finalteam/loacompass/dto/SignupRequest.java, backend/src/main/java/com/finalteam/loacompass/entity/Role.java, backend/src/main/java/com/finalteam/loacompass/entity/User.java, backend/src/main/java/com/finalteam/loacompass/repository/UserRepository.java, backend/src/main/java/com/finalteam/loacompass/security/JwtAuthenticationFilter.java, backend/src/main/java/com/finalteam/loacompass/security/JwtUtil.java, backend/src/main/java/com/finalteam/loacompass/security/SecurityConfig.java, backend/src/main/java/com/finalteam/loacompass/service/UserService.java, backend/src/main/resources/application.yml, frontend/src/components/Navbar.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/Register.jsx
로그인,회원가입 기능구현
---
---
---
---
---
=> 로그인,회원가입 기능구현

frontend/src/components/CharacterProfileCard.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/pages/MyPage.jsx
즐겨찾기 기능 회복시키고, 검색창 두개 뜨는거 고침
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 마이페이지랑 검색창두개뜨는거 고침

backend/src/main/java/com/finalteam/loacompass/client/LostArkClient.java, backend/src/main/java/com/finalteam/loacompass/population/controller/PopulationStatisticsController.java, backend/src/main/java/com/finalteam/loacompass/population/dto/ServerClassDistributionDto.java, backend/src/main/java/com/finalteam/loacompass/population/dto/ServerPopulationDto.java, backend/src/main/java/com/finalteam/loacompass/population/entity/CharacterRecord.java, backend/src/main/java/com/finalteam/loacompass/population/entity/RecordSourceType.java, backend/src/main/java/com/finalteam/loacompass/population/repository/CharacterRecordRepository.java, backend/src/main/java/com/finalteam/loacompass/population/service/PopulationStatisticsService.java, backend/src/main/java/com/finalteam/loacompass/security/SecurityConfig.java, backend/src/main/java/com/finalteam/loacompass/service/CharacterService.java
캐릭터 검색하면
통계에 필요한 정보들을 db에 저장합니다.(1640레벨 이상만 저장함)
그리고 db에서 이 정보들을 꺼내서 프론트로 그래프 등 구현을할때는 
http://localhost:8080/api/statistics/server-count
http://localhost:8080/api/statistics/server-class-distribution
여기에 나오는 json 요청받아서합니다.(현재 2개밖에없는데 더 추가할예정 1~2개정도 더)
우선 캐릭터 검색해보고  자기 db에 저장 잘되는지 확인해보세요
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 캐릭터 검색시 db 저장(1640이상)

frontend/src/pages/DiscordCallback.jsx
디스코드로그인 로딩화면 수정함. 너무 빨라서 캡쳐는 못함..
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 디스코드로그인 로딩화면

frontend/src/components/CharacterProfileCard.jsx, frontend/src/pages/CharacterSearch.jsx
즐겨찾기 별 체크안되길래 수정.
저부분 코드 누락됐었음
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 즐겨찾기 안되는 현상 수정

frontend/src/components/CharacterProfileCard.jsx, frontend/src/components/CharacterSearchInput.jsx, frontend/src/components/Navbar.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/pages/SassagaeCrawler.jsx, frontend/src/routes/AppRouter.jsx, package-lock.json, package.json
사사게 게시판도 디자인 변경
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 즐찾 검색기록 통합

backend/src/main/java/com/finalteam/loacompass/LoaCompassApplication.java, backend/src/main/java/com/finalteam/loacompass/client/LostArkClient.java, backend/src/main/java/com/finalteam/loacompass/population/controller/NicknameCollectorController.java, backend/src/main/java/com/finalteam/loacompass/population/controller/PopulationStatisticsController.java, backend/src/main/java/com/finalteam/loacompass/population/entity/FailedNickname.java, backend/src/main/java/com/finalteam/loacompass/population/repository/CharacterRecordRepository.java, backend/src/main/java/com/finalteam/loacompass/population/repository/FailedNicknameRepository.java, backend/src/main/java/com/finalteam/loacompass/population/scheduler/NicknameCollectorScheduler.java, backend/src/main/java/com/finalteam/loacompass/population/service/NicknameCollectorService.java, backend/src/main/java/com/finalteam/loacompass/population/service/PopulationStatisticsService.java, backend/src/main/java/com/finalteam/loacompass/security/SecurityConfig.java, backend/src/main/java/com/finalteam/loacompass/service/CharacterService.java, backend/src/main/java/com/finalteam/loacompass/util/NicknameGenerator.java
http://localhost:8080/api/admin/collect-random?count=10      
위 url로 요청하면 10개 닉네임 자동으로 랜덤생성해서  아이디 검색을함. (loacompass/util/NicknameGenerator.java)
만약 랜덤생성한 닉네임이 실제 존재하고  조건(아이템 레벨 1640이상)에 맞다면  db에 저장함
검색 결과가 없고, 조건에 안맞는다면  나중에 중복 검색 방지를 위해  failed_nickname 테이블에 저장하고  다음 검색 대상에서 제외됨
---
실제로 코드는 
새벽 04시에 자동으로 500개를 검색하게 구현했음 (스케줄러 어노테이션)
계속 그렇게 검색결과를 쌓아서 데이터를 늘리고 통계 범위를 확장하는게 목표
주의할점은
로스트아크 오픈 api는 분당 100개 요청으로 제한이 걸려있음
따로 과도하게 요청하면 차단받을수있으니까 유의
---
---
(필요 시 스크린샷 첨부)
---
---
=> 닉네임자동생성기, db저장

backend/src/main/java/com/finalteam/loacompass/population/controller/PopulationStatisticsController.java, backend/src/main/java/com/finalteam/loacompass/population/repository/CharacterRecordRepository.java, backend/src/main/java/com/finalteam/loacompass/population/service/PopulationStatisticsService.java, frontend/src/routes/AppRouter.jsx
라우터에서 characterpage  비어있는거 들어가서 에러뜸. 임시로 삭제해둠
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 라우터 characterpage 삭제, 닉네임생성- db저장 수정

backend/src/main/java/com/finalteam/loacompass/controller/UserController.java, backend/src/main/java/com/finalteam/loacompass/dto/JwtResponse.java, backend/src/main/java/com/finalteam/loacompass/entity/User.java, frontend/src/pages/MyPage.jsx
가입날짜가 계속 오늘날짜로 초기화되길래 회원가입햇을때 날짜로 고정해둠
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 마이페이지 가입날짜수정

frontend/src/components/Score/statHelper.js
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 악세서리부분 null값 안전검사 추가

analysis/population_forecaster.py, app.py, backend/src/main/java/com/finalteam/loacompass/config/RestTemplateConfig.java, backend/src/main/java/com/finalteam/loacompass/population/service/NicknameCollectorService.java, backend/src/main/java/com/finalteam/loacompass/util/NicknameGenerator.java, nickname_generator.py, package-lock.json, package.json
밑에 설치 안돼있으면 설치
npm install lucide-react
pip install mysql-connector-python
pip install pandas
pip install pandas mysql-connector-python numpy
pip install prophet
pip install pandas matplotlib
java로 랜덤 닉네임을 생성해왔는데
실제 닉네임 수집률이 너무 낮음
추가적으로 python에서 라이브러리를 사용해 조금더 효율적인 방법 필요
파이썬의  n-gram라이브러리로 바꿈.  이제 flask(파이썬)서버 실행할때마다 현재 db에있는 닉네임들 얘가 학습해서 좀더 있을법한 아이디 생성할 수 있음 (https://datasciencebeehive.tistory.com/114)
python app.py 실행한뒤  
http://localhost:8080/api/admin/collect-random?count=200   
이거로 수집함.  뒤에 숫자(200)은 닉네임 수집할 개수. 10으로 바꾸면 10개만 수집
밑에는 ai 분석 서버인원 결과
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> flask로 닉네임생성기 이전

frontend/src/components/Score/ScoreRow.jsx, frontend/src/components/Score/statHelper.js, frontend/src/pages/CharacterSearch.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 보석 점수계산 추가

backend/src/main/java/com/finalteam/loacompass/security/SecurityConfig.java, frontend/src/components/Navbar.jsx, frontend/src/routes/AppRouter.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 게시판 연결+시큐리티허용

frontend/src/App.jsx, frontend/src/components/Layout.jsx, frontend/src/pages/BoardDetail.jsx, frontend/src/pages/BoardList.jsx, frontend/src/pages/BoardWrite.jsx, frontend/src/pages/Boards.jsx, frontend/src/routes/AppRouter.jsx, package-lock.json
게시판 디자인 좀 바꿨고 다크모드도 approuter에 넣어놧음
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 게시판 디자인&다크모드 렌더링

frontend/src/components/Advertisement.jsx, frontend/src/components/CharacterSearchInput.jsx, frontend/src/components/DarkToggle.jsx, frontend/src/components/EventSection.jsx, frontend/src/components/Footer.jsx, frontend/src/components/Navbar.jsx, frontend/src/components/UpdateList.jsx, frontend/src/components/WelcomeBanner.jsx, frontend/src/pages/AIAssistant.jsx, frontend/src/pages/Home.jsx, frontend/src/routes/AppRouter.jsx
프론트엔드 이것저것
로고, 네비게이션바, 색감이나 위치조정
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 프론트엔드 이것저것

frontend/src/routes/AppRouter.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> Kde footerfix

backend/src/main/java/com/finalteam/loacompass/controller/GeminiController.java, backend/src/main/java/com/finalteam/loacompass/security/SecurityConfig.java, backend/src/main/resources/application.yml, frontend/src/components/ChatMessage.jsx, frontend/src/components/Footer.jsx, frontend/src/components/Navbar.jsx, frontend/src/components/WelcomeBanner.jsx, frontend/src/pages/AIAssistant.jsx, frontend/src/routes/AppRouter.jsx, frontend/src/services/gemini.js, frontend/vite.config.js
ai 만들엇는데 무료끝났다고 오늘은 못한다고함 내일 오전 9시에 되는지 확인해야함... 일단 내 카드등록해놧음
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> gemini ai 챗봇

backend/src/main/java/com/finalteam/loacompass/population/controller/PopulationStatisticsController.java, backend/src/main/java/com/finalteam/loacompass/population/dto/TopCharacterDto.java, backend/src/main/java/com/finalteam/loacompass/population/entity/CharacterRecord.java, backend/src/main/java/com/finalteam/loacompass/population/repository/CharacterRecordRepository.java, backend/src/main/java/com/finalteam/loacompass/population/service/PopulationStatisticsService.java, backend/src/main/java/com/finalteam/loacompass/service/CharacterService.java, frontend/package-lock.json, frontend/package.json, frontend/src/components/Score/statHelper.js, frontend/src/components/statistics/TopPlayerCard.jsx
---
db에 저장된 캐릭터 데이터중에 이미지 있는 데이터들만 나옴(백앤드쪽 수정하긴할거임. 이미지없어도 어쨌든 순위는 제대로 나와야하니까)
npm install react-icons     << 프론트쪽에서 이거 인스톨하고
ALTER TABLE character_record ADD character_image VARCHAR(255);    << mysql 워크벤치에서 이거 실행해주세요
---
(필요 시 스크린샷 첨부)
---
---
=> top5playerCard

frontend/package-lock.json, frontend/src/components/statistics/TopPlayerCard.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/routes/AppRouter.jsx, package-lock.json, package.json
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 통êê계 닉ë네임바로가기

frontend/src/components/ShopList.jsx, frontend/src/components/statistics/ServerPopulationChart.jsx, frontend/src/components/statistics/StatisticsTabs.jsx, frontend/src/components/statistics/TotalClassChart.jsx, frontend/src/components/statistics/TotalLevelChart.jsx, frontend/src/pages/AIAssistant.jsx, frontend/src/pages/Boards.jsx, frontend/src/pages/Statistics.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 통계 스타일 변경. 마리샵 로딩중 추가

frontend/src/components/statistics/StatisticsTabs.jsx, frontend/src/components/statistics/TopPlayerCard.jsx, frontend/src/pages/BoardList.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 게시판 수정, 화살표 수정

analysis/population_forecaster.py, analysis/population_predictor.py, app.py, frontend/src/components/statistics/AIAnalysisModal.jsx, frontend/src/components/statistics/AISidePanel.jsx, frontend/src/components/statistics/StatisticsTabs.jsx
분석 요약 부분 헤더에 색상 넣음.  (색깔이상하면 수정가능)
탭형식으로 전환함.
다음주 평균레벨 상승 예측 직업 분석
---
---
(필요 시 스크린샷 첨부)
---
---
=> create sidepanel tab

frontend/src/components/AbilityStone/AbilityStoneCard.jsx, frontend/src/components/Accessory/AccessoryCard.jsx, frontend/src/components/Bracelet/BraceletCard.jsx, frontend/src/components/Engravings/EngravingsCard.jsx, frontend/src/components/Equipment/EquipmentAccessoryRow.jsx, frontend/src/components/Score/ScoreRow.jsx, frontend/src/components/Simulation/SimulationEngravingsCard.jsx, frontend/src/components/Simulation/SimulationEquipmentCard.jsx, frontend/src/components/Simulation/SimulationRow.jsx, frontend/src/pages/CharacterSearch.jsx, frontend/src/pages/CharacterSimulation.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 시뮬레이션 페이지 프론트 제작 및 점수 적용(각인,보석x)

frontend/src/components/AbilityStone/AbilityStoneCard.jsx, frontend/src/components/Score/ScoreRow.jsx, frontend/src/components/Simulation/SimulationEngravingsCard.jsx, frontend/src/components/Simulation/SimulationGemCard.jsx, frontend/src/components/Simulation/SimulationGemList.jsx, frontend/src/components/Simulation/SimulationRow.jsx, frontend/src/pages/CharacterSimulation.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 시뮬레이션 페이지 프론트 제작 및 점수 적용,캐릭터검색페이지 어빌리티스톤 ui개선

frontend/.env.production
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 고정ip주소로 변경

frontend/src/components/Simulation/SimulationEngravingsCard.jsx, frontend/src/components/Simulation/SimulationEquipmentCard.jsx, frontend/src/components/Simulation/SimulationGemCard.jsx
장비쪽 문제있음. null 일경우 빈배열로 나오게 방어코드추가하니까 화면은 안터짐
유물장비껴있거나 무기초월안되어있거나 이런 캐릭터들은 장비관련해서 null나오는듯.  수정해야댐
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 시뮬레이션장비방어코드추가

frontend/src/components/CharacterSearchInput.jsx, frontend/src/components/Navbar.jsx
---
---
---
(필요 시 스크린샷 첨부)
---
---
=> 스크린샷검색 UI개선 및 코드 정리
